language: node_js
sudo: false
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
      - ubuntu-toolchain-r-test
    packages:
      - google-chrome-stable
      - g++-4.8
node_js:
  - '5.1'
before_script:
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - sleep 3
  - npm i -g bower gulp
  - bower i
script:
  - npm test
env:
  global:
    - CXX=g++-4.8 BROWSERS=Firefox
